_wandb:
    value:
        cli_version: 0.27.0
        e:
            j8nnxi9qqlbwfo0ms5u4fy0txkzprxcj:
                args:
                    - --config
                    - "10"
                codePath: src/prunning/main.py
                codePathLocal: main.py
                email: kashifriyaz01@gmail.com
                executable: /home/jovyan/GMAR-Plus-with-pruning/src/prunning/venv/bin/python3
                git:
                    commit: e39884155624817430d66d58c953385c93d4128e
                    remote: https://kashif003:@github.com/kashif003/GMAR-Plus-with-pruning.git
                host: ki-jnbk-0d6a
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.39
                program: /home/jovyan/GMAR-Plus-with-pruning/src/prunning/main.py
                python: CPython 3.12.3
                root: /home/jovyan/GMAR-Plus-with-pruning/src/prunning
                startedAt: "2026-06-02T09:48:14.878985Z"
                writerId: j8nnxi9qqlbwfo0ms5u4fy0txkzprxcj
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 63
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 63
            "3":
                - 13
                - 16
            "4": 3.12.3
            "5": 0.27.0
            "6": 4.57.1
            "12": 0.27.0
            "13": linux-x86_64
Pruning precentage:
    value: 10
