_wandb:
    value:
        cli_version: 0.27.0
        e:
            b10acczn5w6vsl16vc7nvoy4k1xpuwne:
                args:
                    - --config
                    - "40"
                codePath: src/prunning/main.py
                codePathLocal: main.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "19123537334272"
                        used: "16684420390912"
                email: kashifriyaz01@gmail.com
                executable: /home/jovyan/GMAR-Plus-with-pruning/src/prunning/venv/bin/python3
                git:
                    commit: dc10374dacae82a73e37afa5187ad7665046ca7e
                    remote: https://kashif003:@github.com/kashif003/GMAR-Plus-with-pruning.git
                gpu: NVIDIA A100-PCIE-40GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-58e6b591-fda2-1ecc-f6c6-9a1ac8c4cd33
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-6b2e87f8-0094-f585-3b13-7b2817bc52c8
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-9db3ff93-0cb9-384c-f1df-dedcd47f66ab
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-0e1f80a5-bbe8-f9b9-6ee0-db21a446ddd6
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-901d6d14-07e0-5eb5-78ad-15971277152d
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-cfc7654f-2288-440e-cbfe-a03fc31ae340
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-7daf7646-467b-bb44-e4c0-17e8028f3d93
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-6dcb2e78-8034-42d7-258c-6e261dc1fb4f
                host: ki-jnbk-0d6a
                memory:
                    total: "1082014359552"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.39
                program: /home/jovyan/GMAR-Plus-with-pruning/src/prunning/main.py
                python: CPython 3.12.3
                root: /home/jovyan/GMAR-Plus-with-pruning/src/prunning
                startedAt: "2026-06-02T12:03:42.128965Z"
                writerId: b10acczn5w6vsl16vc7nvoy4k1xpuwne
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 63
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 63
            "3":
                - 13
                - 16
            "4": 3.12.3
            "5": 0.27.0
            "6": 4.57.1
            "12": 0.27.0
            "13": linux-x86_64
Pruning precentage:
    value: 40
